server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # This redirects any request starting with /api to your backend container
    location /api/ {
        proxy_pass http://cerebro-api:3000; # Internal Docker DNS
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}